import type { RegistryRow } from "../src/registry.ts";

// Hermetic mini-registry for tests. Never reads ../aidep-registry.
export const MINI_REGISTRY: RegistryRow[] = [
  {
    id: "openai:endpoint:assistants-api",
    provider: "openai",
    surface: "endpoint",
    api_ids: ["/v1/assistants", "/v1/threads"],
    status: "deprecated",
    announced: "2025-08-26",
    dies: "2026-08-26",
    dies_is_earliest_possible: false,
    replacement_id: "openai:endpoint:responses-api",
    replacement_notes: "Migrate to the Responses API.",
    migration_url: "https://platform.openai.com/docs/assistants/migration",
    source_url: "https://platform.openai.com/docs/deprecations",
    verified_at: "2026-08-01",
    platform: "first-party",
  },
  {
    // a dictionary-word id: only counts inside matched quotes
    id: "openai:model:ada",
    provider: "openai",
    surface: "model",
    api_ids: ["ada"],
    status: "retired",
    announced: "2023-07-06",
    dies: "2024-01-04",
    dies_is_earliest_possible: false,
    replacement_id: "babbage-002",
    replacement_notes: null,
    migration_url: null,
    source_url: "https://developers.openai.com/api/docs/deprecations",
    verified_at: "2026-08-01",
    platform: "first-party",
  },
  {
    // ada's named replacement, itself dying: the two-hop chain the lookup walks
    id: "openai:model:babbage-002",
    provider: "openai",
    surface: "model",
    api_ids: ["babbage-002"],
    status: "deprecated",
    announced: "2026-03-28",
    dies: "2026-09-28",
    dies_is_earliest_possible: false,
    replacement_id: "gpt-4o-mini",
    replacement_notes: null,
    migration_url: null,
    source_url: "https://developers.openai.com/api/docs/deprecations",
    verified_at: "2026-08-01",
    platform: "first-party",
  },
  {
    id: "openai:model:gpt-4-turbo",
    provider: "openai",
    surface: "model",
    api_ids: ["gpt-4-turbo"],
    status: "deprecated",
    announced: "2026-04-23",
    dies: "2026-10-23",
    dies_is_earliest_possible: true,
    replacement_id: null,
    replacement_notes: null,
    migration_url: null,
    source_url: "https://platform.openai.com/docs/deprecations",
    verified_at: "2026-08-01",
    platform: "first-party",
  },
  {
    id: "anthropic:model:claude-3-5-sonnet-20241022",
    provider: "anthropic",
    surface: "model",
    api_ids: ["claude-3-5-sonnet-20241022"],
    status: "retired",
    announced: "2025-07-28",
    dies: "2025-10-28",
    dies_is_earliest_possible: false,
    replacement_id: "anthropic:model:claude-sonnet-4-6",
    replacement_notes: null,
    migration_url: null,
    source_url: "https://docs.anthropic.com/en/docs/about-claude/model-deprecations",
    verified_at: "2026-08-01",
    platform: "first-party",
  },
  {
    id: "openai:model:gpt-5-2025-08-07",
    provider: "openai",
    surface: "model",
    api_ids: ["gpt-5-2025-08-07"],
    status: "deprecated",
    announced: "2026-06-11",
    dies: "2026-12-11",
    dies_is_earliest_possible: false,
    replacement_id: "openai:model:gpt-5.6-sol",
    replacement_notes: null,
    migration_url: null,
    source_url: "https://platform.openai.com/docs/deprecations",
    verified_at: "2026-08-01",
    platform: "first-party",
  },
  {
    id: "google:model:gemini-2.0-flash-001",
    provider: "google",
    surface: "model",
    api_ids: ["gemini-2.0-flash-001"],
    status: "retired",
    announced: "2025-12-01",
    dies: "2026-06-01",
    dies_is_earliest_possible: false,
    replacement_id: null,
    replacement_notes: null,
    migration_url: null,
    source_url: "https://ai.google.dev/gemini-api/docs/deprecations",
    verified_at: "2026-08-01",
    platform: "first-party",
  },
  {
    id: "anthropic:param:temperature-top-p-top-k",
    provider: "anthropic",
    surface: "param",
    api_ids: ["temperature", "top_p", "top_k"],
    status: "deprecated",
    announced: "2026-05-14",
    dies: null,
    dies_is_earliest_possible: false,
    replacement_id: null,
    replacement_notes: "Sampling params are ignored on newer Claude models.",
    migration_url: null,
    source_url: "https://docs.anthropic.com/en/api/messages",
    verified_at: "2026-08-01",
    platform: "first-party",
  },
];
